### ISSUE TITLE
Fails to build from "Deploy on Netlify" button

### ISSUE THREAD

**Issue by jacebenson** [philhawksworth/linkylinky#3]
Here's the output;

```
9:05:42 AM: [WARNING] We are experiencing internal issues storing deploy logs. Some log lines may be missing.
9:05:42 AM: Build ready to start
9:05:45 AM: build-image version: 9e0f207a27642d0115b1ca97cd5e8cebbe492f63
9:05:45 AM: build-image tag: v3.3.2
9:05:45 AM: buildbot version: 75cd99f62ada9e21edea53208e8baf0eab85a045
9:05:45 AM: Fetching cached dependencies
9:05:45 AM: Failed to fetch cache, continuing with build
9:05:45 AM: Starting to prepare the repo for build
9:05:46 AM: No cached dependencies found. Cloning fresh repo
9:05:46 AM: git clone https://github.com/philhawksworth/linkylinky
9:05:46 AM: Preparing Git Reference refs/heads/master
9:05:47 AM: Found netlify.toml. Overriding site configuration
9:05:47 AM: Different functions path detected, going to use the one specified in the toml file: 'functions' versus '' in the site
9:05:47 AM: Creating functions prep folder
9:05:47 AM: Starting build script
9:05:47 AM: Installing dependencies
9:05:48 AM: Downloading and installing node v10.16.0...
9:05:49 AM: Downloading https://nodejs.org/dist/v10.16.0/node-v10.16.0-linux-x64.tar.xz...
9:05:49 AM: 
######
9:05:49 AM:                                        8.8%
9:05:50 AM: 
#######
9:05:50 AM:                                  10.4%
9:05:50 AM: 
###################
9:05:50 AM:                                 26.7%
9:05:50 AM: #
9:05:50 AM: #
9:05:50 AM: #
9:05:50 AM: #
9:05:50 AM: #
9:05:50 AM: #
9:05:50 AM: #
9:05:50 AM: ###############
9:05:50 AM:                                30.7%
9:05:50 AM: 
############################
9:05:50 AM:                                40.2%
9:05:50 AM: 
###############################
9:05:50 AM: #####                                      51.3%
9:05:50 AM: 
##################################
9:05:50 AM: ############                            64.6%
9:05:50 AM: 
###############################################
9:05:50 AM: #####                      73.2%
9:05:51 AM: #
9:05:51 AM: #
9:05:51 AM: #
9:05:51 AM: #
9:05:51 AM: #
9:05:51 AM: #
9:05:51 AM: #
9:05:51 AM: #
9:05:51 AM: #######
9:05:51 AM: #########################################                  78.3%
9:05:51 AM: 
######################
9:05:51 AM: ####################################                81.5%
9:05:51 AM: 
##################################################
9:05:51 AM: ####################    97.4%
9:05:51 AM: 
###################################
9:05:51 AM: ##################################### 100.0%
9:05:51 AM: Computing checksum with sha256sum
9:05:51 AM: Checksums matched!
9:05:55 AM: Now using node v10.16.0 (npm v6.9.0)
9:05:55 AM: Attempting ruby version 2.6.2, read from environment
9:05:56 AM: Using ruby version 2.6.2
9:05:57 AM: Using PHP version 5.6
9:05:57 AM: Started restoring cached node modules
9:05:57 AM: Finished restoring cached node modules
9:05:57 AM: Started restoring cached yarn cache
9:05:57 AM: Finished restoring cached yarn cache
9:05:57 AM: Installing yarn at version 1.13.0
9:05:57 AM: Installing Yarn!
9:05:57 AM: > Downloading tarball...
9:05:57 AM: [1/2]: https://yarnpkg.com/
9:05:57 AM: downloads/1.13.0/yarn-v1.13.0.tar.gz --> /tmp/yarn.tar.gz.RWpYLIQhgX
9:05:57 AM:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
9:05:57 AM:                        Dload  Upload   Total   Spent    Left  Speed
9:05:57 AM: 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
9:05:57 AM: 
100    93  100    93    0     0    388
9:05:57 AM:      0 --:--:-- --:--:-- --:--:--   389
9:05:58 AM: 
100   609    0   609    0     0    753      0 --:--:-- --:--:-- --
9:05:58 AM: :--:--   753
9:05:58 AM: 
  0     0    0     0    0     0      0      0
9:05:58 AM:  --:--:-- --:--:-- --:--:--     0
9:05:58 AM: 
100 1142k  100 1142k
9:05:58 AM: 0     0   901k      0  0:00:01  0:00:01 --:--:-- 3112k
9:05:58 AM: [2/2]: https://yarnp
9:05:58 AM: kg.com/downloads/1.13.0/yarn-v1.13.0.tar.gz.asc --> /tmp/yarn.tar.gz.RWpYLIQhgX.asc
9:05:58 AM: 
100    97  100    97    0     0   2249      0 --:--:-- --:--:-- --:-
9:05:58 AM: -:--  2249
9:05:58 AM: 
100   613    0   613    0     0   4167
9:05:58 AM:      0 --:--:-- --:--:-- --:--:--  4167
9:05:58 AM: 
100   832  100   832    0
9:05:58 AM:    0   3919      0 --:--:-- --:--:-- --:--:--  3919
9:05:58 AM: > Verifying integrity...
9:05:58 AM: gpg: Signature made Tue 18 Dec 2018 04:04:55 PM UTC using RSA key ID B6FF4DE3
9:05:58 AM: gpg: Good signature from "Yarn Packaging <yarn@dan.cx>"
9:05:58 AM: gpg: Note: This key has expired!
9:05:58 AM: Primary key fingerprint: 72EC F46A 56B4 AD39 C907  BBB7 1646 B01B 86E5
9:05:58 AM:  0310
9:05:58 AM:      Subkey fingerprint: E219 30C4 D0A4 AA46 1858  1F7A E074 D16E B6FF 4DE3
9:05:58 AM: > GPG signature looks good
9:05:58 AM: > Extracting to ~/.yarn...
9:05:59 AM: > Adding to $PATH...
9:05:59 AM: > We've added the following to your /opt/buildhome/.profile
9:05:59 AM: > If this isn't the profile of your current shell then please add the following to your correct profile:
9:05:59 AM: export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
9:05:59 AM: 
9:05:59 AM: > Successfully installed Yarn 1.13.0! Please open another terminal where the `yarn` command will now be available.
9:06:00 AM: Installing NPM modules using Yarn version 1.13.0
9:06:00 AM: yarn install v1.13.0
9:06:01 AM: [1/4] Resolving packages...
9:06:01 AM: [2/4] Fetching packages...
9:06:10 AM: error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9". Got "10.16.0"
9:06:10 AM: failed during stage 'building site': Build script returned non-zero exit code: 1
```

**Comment by jacebenson** [comment]
Adding a .nvmrc file with content of `8.9.0` seems to fix this. #4 has the fix in the PR.

**Comment by iamskok** [comment]
Hey @philhawksworth! 

Super cool project and I really wanted to play around with it, but I can confirm that Netlify deploy button doesn't work. 

[Error log](https://app.netlify.com/sites/url-shortner/deploys/5d43e5e7451676707a0e828e) 

```bash
12:27:57 AM: error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9". Got "10.16.1"
12:27:57 AM: error Found incompatible module.
```

After that I have updated all the dependencies to the latest versions but looks like it's not the only issue:

```
12:31:57 AM: $ netlify-lambda build src/lambda
12:31:58 AM: assert.js:339
12:31:58 AM:     throw err;
12:31:58 AM:     ^
12:31:58 AM: AssertionError [ERR_ASSERTION]: Task function must be specified
12:31:58 AM:     at Gulp.set [as _setTask] (/opt/build/repo/node_modules/undertaker/lib/set-task.js:10:3)
12:31:58 AM:     at Gulp.task (/opt/build/repo/node_modules/undertaker/lib/task.js:13:8)
12:31:58 AM:     at Object.<anonymous> (/opt/build/repo/gulpfile.js:55:6)
12:31:58 AM:     at Module._compile (internal/modules/cjs/loader.js:778:30)
12:31:58 AM:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
12:31:58 AM:     at Module.load (internal/modules/cjs/loader.js:653:32)
12:31:58 AM:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
12:31:58 AM:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
12:31:58 AM:     at Module.require (internal/modules/cjs/loader.js:692:17)
12:31:58 AM:     at require (internal/modules/cjs/helpers.js:25:18)
```

[Error log](https://app.netlify.com/sites/url-shortner/deploys/5d43e6d03ec4e600080d0f3d)

Do you have any plans fixing it or can you assist in debugging it, please?

**Comment by jacebenson** [comment]
I have it fixed in #4 

You can deploy from that fork until this is merged...

https://app.netlify.com/start/deploy?repository=https://github.com/jacebenson/linkylinky

Or if you have you're own fork.  create a file at ./.nvmrc with a value of 8.9.0 like it is here;
https://github.com/jacebenson/linkylinky
